### ISSUE TITLE
Consider setting omit-Origin-header-flag for same origin requests

### ISSUE THREAD

**Issue by tyoshino** [whatwg/xhr#31] opened 2015-11-24 08:24 UTC
Created in response to https://github.com/whatwg/fetch/issues/91#issuecomment-159190323.

As @yutakahirano reported in https://github.com/whatwg/fetch/issues/91#issuecomment-144348029, Chrome (only GET/HEAD) and Firefox (also for POSTs) are not sending the `Origin` header for same origin requests. The background for Chrome (WebKit) is a little complicated (see https://github.com/whatwg/fetch/issues/91#issuecomment-128261982).

As it's been so for long time, we could make XHR an exception (i.e. no Origin for same origin requests).

**Comment by tyoshino** [comment] 2015-12-11 04:55
See also https://github.com/whatwg/fetch/issues/172

**Comment by annevk** [comment] 2015-12-15 16:48
So it seems we need something more complicated since a same-origin to cross-origin redirect as initial response would cause the header to be included, right?

**Comment by tyoshino** [comment] 2015-12-16 05:08
I think so. If we adopt the change, i.e. no Origin header for same-origin, we should align Origin header inclusion yes/no with cross origin yes/no. When we enter cross-origin processing state in response to same to cross redirect, we should include the Origin header in the next, now cross-origin, request.

**Comment by tyoshino** [comment] 2015-12-16 05:54
Maybe `HTTP-network-or-cache fetch` should be passed `CORS flag` and use it to decide whether or not to append the Origin header.

**Comment by annevk** [comment] 2015-12-16 09:42
The problem is that we also use the `Origin` header for `<form method=POST>` and some other things? What logic does Blink use at the moment?

**Comment by tyoshino** [comment] 2015-12-16 11:09
It's complicated. @hiroshige-g is checking Blink code to sort it out now.

**Comment by wanderview** [comment] 2016-05-16 15:03
Related gecko bug:  https://bugzilla.mozilla.org/show_bug.cgi?id=1272302

**Comment by annevk** [comment] 2016-12-08 01:45
FWIW, this is being fixed by https://github.com/whatwg/fetch/issues/225. We're just obsoleting the need for the flag and instead directly check the methods in use (or the CORS flag).

**Closed** 2016-12-09 07:37 UTC
