### ISSUE TITLE
Synchronous XMLHttpRequest outside of workers deprecation is not a good idea.

### ISSUE THREAD

**Issue by BourgeoisBear** [whatwg/xhr#60] opened 2016-03-16 23:31 UTC
In _most_ cases, I agree that synchronous requests should be avoided.  I fully understand why they should be avoided.  I strongly _disagree_ with the decision to deprecate them.  We are talking about programmers and tools here, not children and knives.

In some cases, synchronous requests are a life saver:  Let's say I have a 3rd party component, like jQueryUI datepicker, and there is a user-override-able callback for a feature of the control (like getting the current time).  In this case, we'll get the time from the server with an ajax request (since we can't assume the clock on the client side is correct).  

If that request _has_ to be asynchronous, how do I keep the rest of the 3rd party code from merrily chugging away before I get the date back from the server?  Continuations aren't much help here (unless I want to wrap the remainder of each callback-calling function in the 3rd party library as a function passed to a continuation).

**Comment by annevk** [comment] 2016-03-17 05:01
Make sure you have the correct time before you expose the control. In any event, this is a duplicate of #20.

**Closed by annevk** 2016-03-17 05:01 UTC

**Comment by BourgeoisBear** [comment] 2016-03-17 14:58
In this particular case, the control is persistent and used for repeated submissions, so we still need to be able to get the time after initialization.  I'll just add it to #20.
