### ISSUE TITLE
jquery.js:9615 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

### ISSUE THREAD

**Issue by Rheetuparna** [whatwg/xhr#139] opened 2017-05-19 01:14 UTC

**Comment by annevk** [comment] 2017-05-19 07:28
You should really report this issue to jQuery. Dupe of #20.

**Closed by annevk** 2017-05-19 07:28 UTC
