### ISSUE TITLE
I have a problem?

### ISSUE THREAD

**Issue by Gracian1** [whatwg/xhr#147] opened 2017-08-09 08:10 UTC
I'm trying to work with ajax but browser telling me this issue,
Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.

why?

**Comment by annevk** [comment] 2017-08-09 08:22
The reason is right there in the message. Duplicate of #20 for all intents and purposes.

**Closed by annevk** 2017-08-09 08:22 UTC
