### ISSUE TITLE
Allow to send body within GET http requests

### ISSUE THREAD

**Issue by VitaliiOdiichuk** [whatwg/xhr#351] opened 2022-07-19 15:45 UTC
As per [spec](https://httpwg.org/specs/rfc7231.html#GET) GET request is not prohibited to have a body please allow set not empty body for GET requests.

**Comment by domenic** [comment] 2022-07-20 00:48
Dupe of https://github.com/whatwg/fetch/issues/83.

**Closed by domenic** 2022-07-20 00:48 UTC

**Comment by Gerard19742608jourdain** [comment] 2022-07-23 18:10
> As per [spec](https://httpwg.org/specs/rfc7231.html#GET) GET request is not prohibited to have a body please allow set not empty body for GET requests.
