### ISSUE TITLE
XMLHttpRequest

### ISSUE THREAD

**Issue by nhatchett** [whatwg/xhr#193] opened 2018-02-20 17:37 UTC
Why are you removing the abilility to execute an XMLHttpRequest syncronously?

I agree that that misuse of this feature can create unresponsive web pages but careful use (i.e.  in the pagehide event) enables AJAX based feed back mechanisms to work on some popular yet awkward browsers (i.e. Firefox).

Most sensible web developers are aware that misusing this feature is undesirable and use the asyncronous option. I feel that removing such a feature because of its detrimental effects to the end user's experience is a very poor decision akin to chopping of a childs hand because it does not know how to use it.

I assume the decision is based on the lowest common denominator principle - when a few are morons treat us all like morons.

**Comment by annevk** [comment] 2018-02-20 17:48
Please use `navigator.sendBeacon()` instead for that purpose. It's not a good reason for synchronous I/O.

Marking this as a duplicate of #20.

**Closed by annevk** 2018-02-20 17:48 UTC

**Comment by nhatchett** [comment] 2018-02-20 18:53
Hi There

 

Unfortunately 'navigator.sendBeacon()' is Experimental and cannot be used in
a live production application.

 

I need a solution I can rely on being around for the foreseeable future (the
site is currently used by thousands of UK train drivers for safety
training).

 

In short I want to send data to a server when a driver leaves the training
page.

 

Using a synchronous AJAX call is the only way I currently know of updating
my server in the PageHide event that works on the 5 browsers I support
(Google, Apple, Micrososft and Firefox - Desktop and Mobile).

 

This is the ONLY reason, to date, I have found to use synchronous
XMLHttpRequest I/O.

 

My reason for using this feature is because it exists, it works and does not
cause my users any problems which seems like a good reason to me.

 

Regards

 

Nigel

 

 

  _____

**Comment by annevk** [comment] 2018-02-21 08:03
I removed the experimental label from https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon if that's what you're referring to. That was simply out-of-date.
