### ISSUE TITLE
Synchronous XMLHttpRequest 

### ISSUE THREAD

**Issue by Z3TA** [whatwg/xhr#158] opened 2017-10-05 12:36 UTC
Synchronous XMLHttpRequest's can be useful when you want to block the script, for example when loading in modules from cache. Do not deprecate it! There could be an optional console warning if it's not loaded from cache though.

**Comment by annevk** [comment] 2017-10-05 13:05
Even from the cache it's bad as I/O can be rather slow in general. Anyway, this is a duplicate of #20.

**Closed by annevk** 2017-10-05 13:05 UTC

**Comment by Z3TA** [comment] 2017-10-06 08:24
@annevk The push chache is really fast, and I/O is usually not the bottleneck now a days with fast ssd's and GbE. The latency should be below the monitor's refresh rate. But lets say you do load it async, you would still have to wait for it! I would hoever be OK with something like `var foo = await import('./myModule.js');`

**Comment by annevk** [comment] 2017-10-06 08:38
Yes, but at least the UI is not blocked.
