### ISSUE TITLE
xmlHtmlrequest

### ISSUE THREAD

**Issue by sayyadfiroj204** [whatwg/xhr#299] opened 2020-11-24 06:36 UTC
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

**Comment by annevk** [comment] 2020-11-30 08:18
Duplicate of #20.

**Closed by annevk** 2020-11-30 08:18 UTC
